openapi: 3.1.0
info:
  title: Spec Explorer Review Flow
  version: 0.2.0
  description: Contracts for gating Send to Review, archiving reviewed specs, filing change requests, and dispatching tasks.
paths:
  /specs/review:
    get:
      summary: List specs currently in the Review folder
      responses:
        "200":
          description: Specs waiting for reviewer action
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReviewList"
  /specs/{specId}/send-to-review:
    post:
      summary: Move a completed spec from Current Specs to Review when no tasks/checklist items remain
      parameters:
        - in: path
          name: specId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Spec moved to Review
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Specification"
        "409":
          description: Spec still has pending tasks/checklist items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GatingError"
  /specs/{specId}/change-requests:
    post:
      summary: Create a change request for a spec and move spec to reopened
      parameters:
        - in: path
          name: specId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeRequestInput"
      responses:
        "201":
          description: Change request created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChangeRequest"
        "409":
          description: Duplicate change request for this spec/title
  /specs/{specId}/change-requests/{changeRequestId}/send-to-tasks:
    post:
      summary: Dispatch change request to tasks prompt and attach returned tasks
      parameters:
        - in: path
          name: specId
          required: true
          schema:
            type: string
        - in: path
          name: changeRequestId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskDispatchInput"
      responses:
        "200":
          description: Tasks created and linked
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskDispatchResult"
        "503":
          description: Tasks prompt unavailable; change request remains open/blocked
  /specs/{specId}/send-to-archived:
    post:
      summary: Archive a reviewed spec once all blockers are cleared
      parameters:
        - in: path
          name: specId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Spec transitioned to Archived
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Specification"
        "409":
          description: Spec cannot be archived because blockers remain
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArchivalError"
components:
  schemas:
    ReviewList:
      type: object
      properties:
        specs:
          type: array
          items:
            $ref: "#/components/schemas/Specification"
    Specification:
      type: object
      required: [id, title, status]
      properties:
        id:
          type: string
        title:
          type: string
        owner:
          type: string
        status:
          type: string
          enum: [current, review, reopened, archived]
        completedAt:
          type: string
          format: date-time
          nullable: true
        reviewEnteredAt:
          type: string
          format: date-time
          nullable: true
        archivedAt:
          type: string
          format: date-time
          nullable: true
        updatedAt:
          type: string
          format: date-time
        links:
          type: object
          properties:
            specPath:
              type: string
            docUrl:
              type: string
        pendingTasks:
          type: integer
          minimum: 0
        pendingChecklistItems:
          type: integer
          minimum: 0
        changeRequests:
          type: array
          items:
            $ref: "#/components/schemas/ChangeRequest"
    ChangeRequestInput:
      type: object
      required: [title, description, severity]
      properties:
        title:
          type: string
        description:
          type: string
        severity:
          type: string
          enum: [low, medium, high, critical]
        notes:
          type: string
    ChangeRequest:
      allOf:
        - $ref: "#/components/schemas/ChangeRequestInput"
        - type: object
          required: [id, specId, status, submitter, createdAt]
          properties:
            id:
              type: string
            specId:
              type: string
            status:
              type: string
              enum: [open, blocked, inProgress, addressed]
            submitter:
              type: string
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time
            sentToTasksAt:
              type: string
              format: date-time
              nullable: true
            tasks:
              type: array
              items:
                $ref: "#/components/schemas/TaskLink"
            archivalBlocker:
              type: boolean
              description: True when this request prevents archiving
    TaskDispatchInput:
      type: object
      required: [changeRequest]
      properties:
        changeRequest:
          $ref: "#/components/schemas/ChangeRequest"
        spec:
          $ref: "#/components/schemas/Specification"
    TaskLink:
      type: object
      required: [taskId, source, status]
      properties:
        taskId:
          type: string
        source:
          type: string
          enum: [tasksPrompt]
        status:
          type: string
          enum: [open, inProgress, done]
        createdAt:
          type: string
          format: date-time
    TaskDispatchResult:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/TaskLink"
        changeRequestStatus:
          type: string
          enum: [inProgress, blocked]
        message:
          type: string
    GatingError:
      type: object
      properties:
        reason:
          type: string
          enum: [pendingTasks, pendingChecklistItems, alreadyInReview, alreadyArchived]
        pendingTasks:
          type: integer
        pendingChecklistItems:
          type: integer
    ArchivalError:
      type: object
      properties:
        reason:
          type: string
          enum: [openChangeRequests, pendingTasks, pendingChecklistItems, alreadyArchived]
        blockingChangeRequestIds:
          type: array
          items:
            type: string
